/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "qmessages.pb-c.h"
void   qmessage__init
                     (Qmessage         *message)
{
  static Qmessage init_value = QMESSAGE__INIT;
  *message = init_value;
}
size_t qmessage__get_packed_size
                     (const Qmessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t qmessage__pack
                     (const Qmessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t qmessage__pack_to_buffer
                     (const Qmessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Qmessage *
       qmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Qmessage *)
     protobuf_c_message_unpack (&qmessage__descriptor,
                                allocator, len, data);
}
void   qmessage__free_unpacked
                     (Qmessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &qmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tlv__init
                     (Tlv         *message)
{
  static Tlv init_value = TLV__INIT;
  *message = init_value;
}
size_t tlv__get_packed_size
                     (const Tlv *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &tlv__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tlv__pack
                     (const Tlv *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &tlv__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tlv__pack_to_buffer
                     (const Tlv *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &tlv__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tlv *
       tlv__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tlv *)
     protobuf_c_message_unpack (&tlv__descriptor,
                                allocator, len, data);
}
void   tlv__free_unpacked
                     (Tlv *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &tlv__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_message__init
                     (DataMessage         *message)
{
  static DataMessage init_value = DATA_MESSAGE__INIT;
  *message = init_value;
}
size_t data_message__get_packed_size
                     (const DataMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_message__pack
                     (const DataMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_message__pack_to_buffer
                     (const DataMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &data_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataMessage *
       data_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataMessage *)
     protobuf_c_message_unpack (&data_message__descriptor,
                                allocator, len, data);
}
void   data_message__free_unpacked
                     (DataMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &data_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue qmessage__request_type__enum_values_by_number[4] =
{
  { "CREATE", "QMESSAGE__REQUEST_TYPE__CREATE", 0 },
  { "DESTROY", "QMESSAGE__REQUEST_TYPE__DESTROY", 1 },
  { "EXIT", "QMESSAGE__REQUEST_TYPE__EXIT", 3 },
  { "INVALID", "QMESSAGE__REQUEST_TYPE__INVALID", 4 },
};
static const ProtobufCIntRange qmessage__request_type__value_ranges[] = {
{0, 0},{3, 2},{0, 4}
};
const ProtobufCEnumValueIndex qmessage__request_type__enum_values_by_name[4] =
{
  { "CREATE", 0 },
  { "DESTROY", 1 },
  { "EXIT", 2 },
  { "INVALID", 3 },
};
const ProtobufCEnumDescriptor qmessage__request_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "qmessage.RequestType",
  "RequestType",
  "Qmessage__RequestType",
  "",
  4,
  qmessage__request_type__enum_values_by_number,
  4,
  qmessage__request_type__enum_values_by_name,
  2,
  qmessage__request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor qmessage__field_descriptors[4] =
{
  {
    "req",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Qmessage, req),
    &qmessage__request_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_main",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Qmessage, has_thread_main),
    PROTOBUF_C_OFFSETOF(Qmessage, thread_main),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_args",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Qmessage, has_thread_args),
    PROTOBUF_C_OFFSETOF(Qmessage, thread_args),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Qmessage, has_tid),
    PROTOBUF_C_OFFSETOF(Qmessage, tid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned qmessage__field_indices_by_name[] = {
  0,   /* field[0] = req */
  2,   /* field[2] = thread_args */
  1,   /* field[1] = thread_main */
  3,   /* field[3] = tid */
};
static const ProtobufCIntRange qmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor qmessage__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "qmessage",
  "Qmessage",
  "Qmessage",
  "",
  sizeof(Qmessage),
  4,
  qmessage__field_descriptors,
  qmessage__field_indices_by_name,
  1,  qmessage__number_ranges,
  (ProtobufCMessageInit) qmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue tlv__type__enum_values_by_number[2] =
{
  { "data", "TLV__TYPE__DATA", 0 },
  { "stream", "TLV__TYPE__STREAM", 1 },
};
static const ProtobufCIntRange tlv__type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex tlv__type__enum_values_by_name[2] =
{
  { "data", 0 },
  { "stream", 1 },
};
const ProtobufCEnumDescriptor tlv__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "tlv.type",
  "type",
  "Tlv__Type",
  "",
  2,
  tlv__type__enum_values_by_number,
  2,
  tlv__type__enum_values_by_name,
  1,
  tlv__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor tlv__field_descriptors[2] =
{
  {
    "Type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Tlv, type),
    &tlv__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Tlv, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tlv__field_indices_by_name[] = {
  1,   /* field[1] = Length */
  0,   /* field[0] = Type */
};
static const ProtobufCIntRange tlv__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tlv__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "tlv",
  "Tlv",
  "Tlv",
  "",
  sizeof(Tlv),
  2,
  tlv__field_descriptors,
  tlv__field_indices_by_name,
  1,  tlv__number_ranges,
  (ProtobufCMessageInit) tlv__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_message__field_descriptors[1] =
{
  {
    "Data",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DataMessage, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_message__field_indices_by_name[] = {
  0,   /* field[0] = Data */
};
static const ProtobufCIntRange data_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor data_message__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DataMessage",
  "DataMessage",
  "DataMessage",
  "",
  sizeof(DataMessage),
  1,
  data_message__field_descriptors,
  data_message__field_indices_by_name,
  1,  data_message__number_ranges,
  (ProtobufCMessageInit) data_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
